# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Vienna"
    groups:
      github-actions-all:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Vienna"
    groups:
      devcontainers-all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/src/website/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Vienna"
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/src/dashboard/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Vienna"
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/src/website-api/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Vienna"
    groups:
      nuget-all:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/src/dashboard-api/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Vienna"
    groups:
      nuget-all:
        patterns:
          - "*"
